version: "3.8"

services:
  masterfy:
    build: .
    container_name: masterfy_app
    restart: unless-stopped
    ports:
      - "8088:8000"
    volumes:
      # Agora usamos um volume gerenciado pelo Docker, seguro e persistente
      - masterfy_db:/masterfy/data

# Precisamos declarar o volume aqui embaixo tamb√©m
volumes:
  masterfy_db:
    name: masterfy_db