version: "3.8"

services:
  masterfy:
    build: .
    container_name: masterfy_app
    restart: unless-stopped
    ports:
      # Mapeia a porta 8088 do seu Umbrel para a porta 8000 do Masterfy
      # Usamos 8088 por fora para evitar conflito com outros apps do Umbrel
      - "8088:8000"
    volumes:
      # ISSO SALVA SUA VIDA: Mant√©m o banco de dados a salvo fora do container!
      - ./data:/masterfy/data